package com.bikram.service;

import java.io.File;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import com.amazonaws.services.kinesisfirehose.model.S3BackupMode;
import com.bikram.bean.MFABean;
import com.bikram.dao.MFADao;
import com.bikram.dao.MFADaoImpl;
import com.bikram.util.MFAUtil;
import com.bikram.util.S3BucketUtil;
@Repository
@Component
public class MFAServiceImpl implements MFAService,Runnable{
	@Autowired
	MFADao dao;
	private String email;
	private String companyName;
	private String qrPath;
	private String secretKey;
	private String lastCode;
	private String fileName;

	@Override
	public Object generateMfacode(String email, String companyName) {
		try {
			 System.setProperty("java.awt.headless", "true");

		        String secretKey = MFAUtil.getRandomSecretKey();
		        String barCode = MFAUtil.getGoogleAuthenticatorBarCode(secretKey, email, companyName);
		        String tmpDir = System.getProperty("java.io.tmpdir");
		        if (!tmpDir.endsWith(File.separator)) {
		            tmpDir += File.separator;
		        }
		        String lastCode = null;
		        String fileName=System.currentTimeMillis()+"-"+email+".png";
		        this.fileName=fileName;
		        String qrCodePath = System.getProperty("user.home")+File.separator+ fileName;
		        this.email=email;
		        this.companyName=companyName;
		        this.qrPath=qrCodePath;
		        this.secretKey=secretKey;
		        this.lastCode=lastCode;
		        MFAUtil.createQRCode(barCode, qrCodePath, 400, 400);
		        S3BucketUtil.uploadFile(fileName, qrCodePath);
		        System.out.println("\nConfigure the Google Authenticator App by scanning the following QR code image:\n");
		        System.out.println(qrCodePath + "\n");
		        System.out.println("or by manually entering the secret key:\n");
		        System.out.println(secretKey + "\n");
		        System.out.println("Then verify that the 6 digit codes generated by Google Authenticator\n"
		                + "are synchronized with the following (ctrl-c to exit at any time):\n");

		       
		        Thread t1=new Thread(this);
		        t1.start();
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		return S3BucketUtil.downloadFile(this.fileName);
	}

	private void processMFA(String email, String companyName, String secretKey, String qrCodePath, String lastCode,String fileName) {
		while (true) {
		    String code = MFAUtil.getTOTPCode(secretKey);
		    if (!code.equals(lastCode)) {
		        System.out.println(code);
		        dao.insertOrUdateMFA(email, companyName, qrCodePath,code,secretKey,fileName);
		       
		    }
		    lastCode = code;
		    try {
		        Thread.sleep(1000);
		    } catch (InterruptedException e) {};
		}
	}

	@Override
	public void run() {
		processMFA(email, companyName, secretKey, qrPath, lastCode,fileName);
		
	}
	public String validateMFA(String email,String code) {
		return dao.validateMFA(email, code);
	}
}
